# Generated by Django 6.0.2 on 2026-04-18 21:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herederos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoVerificacion',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('es_valido', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='herederos.usuario')),
            ],
            options={
                'db_table': 'codigo_verificacion',
            },
        ),
    ]
